[package]
name = "opengl-window"
version = "0.1.0"
authors = ["pseres <peet.seres@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.29.1"
cgmath = "0.18.0"